### Prod profile

spring:
  config:
    activate:
      on-profile: prod
  main:
    allow-bean-definition-overriding: true
  mvc:
    log-request-details: true

logging:
  level:
    com.chumbok: ERROR