### Prod profile

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.chumbok: ERROR

app:
  logdb:
    endpoint: localhost:3306
    name: logdb
    username: root
    password: root